name: 批量拉取提交
on:
  workflow_dispatch:
    inputs:
      commit-hashes: 
        description: "目标提交的哈希值（用逗号分隔）"
        required: true
      target-repo: 
        description: "目标仓库的URL（格式：owner/repo）"
        required: true
      target-branch: 
        description: "目标仓库的分支名称"
        default: "main"
      git-username: 
        description: "GitHub用户名（需repo权限）"
        required: true
      git-password: 
        description: "GitHub密码/PAT"
        required: true
        sensitive: true  # GitHub企业版支持隐藏输入

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout仓库（完整历史）
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 配置安全环境
        run: |
          # 禁用命令回显防止密码泄露
          set +x
          git config --global credential.helper 'store --file=.git-credentials'
          echo "https://${{ inputs.git-username }}:${{ inputs.git-password }}@github.com" > .git-credentials

      - name: 添加动态远程仓库
        run: |
          git remote remove other-repo || true
          git remote add other-repo "https://${{ inputs.git-username }}:${{ inputs.git-password }}@github.com/${{ inputs.target-repo }}.git"

      - name: 拉取目标分支
        run: git fetch --progress other-repo "${{ inputs.target-branch }}"

      - name: 强制Cherry-pick提交
        run: |
          IFS=',' read -r -a commits <<< "${{ inputs.commit-hashes }}"
          for commit in "${commits[@]}"; do
            echo "正在处理提交: $commit"
            set -o pipefail
            if ! git cherry-pick -m 1 "$commit"; then
              echo "⚡ 检测到冲突，强制应用目标提交..."
              git checkout --theirs . 
              git add .
              git -c user.name="LKDenchin" -c user.email="lkdenchin@lkteam.com" cherry-pick --continue
            fi
          done

      - name: 推送变更到当前分支
        run: |
          git config --global push.default current
          git push origin HEAD --force
